define

## Attributes

# identifiers
campaign-id sub attribute, datatype long;
adgroup-id sub attribute, datatype long;
criterion-id sub attribute, datatype long;

# product id
item-id sub attribute, datatype string;

# common
name sub attribute, datatype string;
type sub attribute, datatype string;
value sub attribute, datatype string;
status sub attribute, datatype string;

## Entities

Enumeration sub entity,
    has name,
    has type,
    has value,
    plays descriptor,
    plays implements;

Mapping sub entity,
    has nominal,
    has key,
    plays descriptor;

# Intagibles

Dimension sub entity is-abstract;

# Tangibles
Campaign sub entity,
    has campaign_id,
    plays parent;

Adgroup sub entity,
	plays parent,
    plays child,
    plays ad-group;

Criterion sub entity,
    has criterion_id,
    has Type,
    plays biddable-criterion;


# meta description of google ads criteria

Criteria sub entity,
    has name,
    has implemented-as,
    plays target;

TargetType sub entity,
    has name,
    plays target-type,
    plays target-criteria;

# Criterion Types

# product partitions are related to their parents explicitly
# via the parent id, using inference and to their siblings
# when their parent-id and dimension-type matches (again, inference)
ProductPartition sub Criterion,
    has parent-id,
	plays product-group;

# Demographics
AgeRange sub Dimension,
    has criterion_id,
    has value;

ProductDimension sub Dimension is-abstract,
    has subtype,
    plays dimension-type;

ProductType sub ProductDimension;
ProductBrand sub ProductDimension;

# Non account level entities
Product sub entity,
    has item_id,
    plays item;

# Groups of pre-defined knowledge

## Relationships

# relates data-object in a generic parent-child fashion
parentship sub relationship is-abstract,
    relates parent,
    relates child;

siblings sub relation,
    relates product-partition;

campaign-adgroup sub parentship;

adgroup-criterion sub relationship,
    relates biddable-criterion,
    relates adgroup;

offer sub relation,
	relates product,
    relates ad-group;

# create product dimension to product partition
# relationship
subdivision sub relation,
    relates product-group,  # parent / subdivision node
    relates dimension-type;  # dimension type segment
    has dimension-value,  # all dimensions values in subdivision
    plays segment;  # for case-value relationships

case-value sub relationship,
    relates product-group,
    relates segment,
    has dimension-type,
    has dimension-value;

targeting-type sub relationship,
    relates targeting,
    relates target-type,
    has created_with;

# again, cool but overcomplicated
criteria-target-mapping sub relationship
    relates target-criteria,
    relates criteria-target;

implementation sub relationship,
    relates implements,
    relates target,
    plays targeting;

criterion-type sub relationship,
    relates targeting-type,
    relates descriptor;